### ISSUE TITLE
Recommended method to run script content only on specific domain paths?

### ISSUE THREAD

**Issue by gingerbeardman** [fphilipe/PageExtender.app#1]
Of course the script will be loaded and executed on any page of the specified domain.

But what is your recommended method to fire only on specific paths?

eg https://www.mediafire.com/file/*

**Comment by gingerbeardman** [comment]
I'm juts doing a simple:

```js
if ( window.location.pathname.includes('/file/') ) {
  // script here
}
```

**Comment by fphilipe** [comment]
I think you're on the right path there 😊 You might also try this, which is "more correct":

```js
window.location.pathname.startsWith('/file/')
```

**Comment by gingerbeardman** [comment]
Yes! Good catch. Boy was I lazy yesterday.

**Comment by ernstwi** [comment]
This is fine for scripts but what about CSS? I worked around it by adding CSS from a script, but a more elegant solution would be nice.

**Comment by ernstwi** [comment]
I gave this a go in #7.
