### ISSUE TITLE
Latest version requires 10.15 Catalina?

### ISSUE THREAD

**Issue by gingerbeardman** [fphilipe/PageExtender.app#10]
Hi Philipe,

I just spotted the latest Mac App Store version now requires 10.15 Catalina.

![Screen shot 2020-05-01 at 09 57 14](https://user-images.githubusercontent.com/49612/80794551-24605300-8b92-11ea-8184-925b32e995f1.png)

But I can still build and run the app myself on Mojave? I have no plans to upgrade right now and I'd prefer to stay on the MAS version.

Deployment target is set to blank in Xcode so assumes latest 10.15 SDK. I am hoping that this 10.15 requirement is an oversight, and that you will be willing to lower it to 10.14 (or 10.13?) with the next update? 

Thoughts appreciated!

Thanks

**Comment by fphilipe** [comment]
Hey @gingerbeardman, thanks for pointing this out. That was definitely not intended 🙈

I've just submitted a new version for review.

**Comment by gingerbeardman** [comment]
Got the new version — thanks again!
