### ISSUE TITLE
CSS style looks really strange in "localhost:8888" URL

### ISSUE THREAD

**Issue by sn0wyfall** [fphilipe/PageExtender.app#13]
Hey,

I'm running a jupyer notebook server in my browser, and I have a CSS style for it that I want to apply. The URL is usually along the lines of `http://localhost:8888/notebooks/My%20Notebooks/Untitled1.ipynb?kernel_name=python3`. I try to style it using a file called `localhost.css` inside my CSS folder. 

However, the result looks really strange: 

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/24374968/85892475-fdec1c00-b7be-11ea-979e-3351fb3c5813.png">

For comparison, here's what it looks like in Chrome using Stylish (note: the text is cut off but it's the style sheet's fault, so just ignore that!):  

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/24374968/85892520-16f4cd00-b7bf-11ea-9c71-b801d02db074.png">

Here is how it looks using Cascadea (font looks different due to the way I configured Chrome): 

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/24374968/85892625-41468a80-b7bf-11ea-8315-b27404f9f6d2.png">

Is there any reason why it looks so strange using PageExtender? I tried putting the style in `default.css` as well, thinking maybe it's a filename/URL incompatibility issue, but it still seems to happen then. 

Any thoughts?

**Comment by sn0wyfall** [comment]
One thing to note is that this is just the python notebook viewer page. The file browser page on localhost seems to be rendered fine!

**Comment by sn0wyfall** [comment]
Okay, I solved it by disabling and re-enabling the extension instead of trying to refresh the page.

**Comment by sn0wyfall** [comment]
Actually it seems like when I refresh the page, it goes back to that weird look. I need to disable and reenable the extension for it to work properly again. Any thoughts on this? Maybe a bug?

**Comment by gingerbeardman** [comment]
Post your CSS
