### ISSUE TITLE
Isn't triggered upon page load in Safari 14

### ISSUE THREAD

**Issue by mpbraendle** [fphilipe/PageExtender.app#14]
Upon page load/reload in Safari 14, CSS code is not injected for a website.
Only loads CSS if in Safari Preferences > Extensions > PageExtender the tickmark is disabled/enabled.

**Comment by gingerbeardman** [comment]
Can I ask how many tabs you have open? 

I've had cases in the past, see #4, where Safari extensions behave erratically when there are more than 50 tabs open. I now use a Tab Count extension to keep track my tabs and do a cull every time I see the number get unconfrotably high.

**Comment by mpbraendle** [comment]
At maximum 10 tabs.
I have one specific CSS that is loaded to distinguish a test from a production system (it just changes the background color for the test system) that would otherwise look the same.

**Comment by mpbraendle** [comment]
If I change all CSS entries to !important, I get the previous function as it worked before with Safari 13.x. It looks like Safari 14 has changed something in the priority of processing the CSS.

**Comment by mpbraendle** [comment]
It must definitely be the order of when the CSS is loaded from SafariPageExtender by Safari 14. CSS expressions that have !important in the original web site style sheet override those which have !important in the SafariPageExtender custom style sheet.

**Comment by fphilipe** [comment]
@mpbraendle everything is working fine on my end. Could you share some more info? What is the selector of the background color set by the page? What is the selector of the CSS that you're injecting?

If you inspect the DOM, you should see that PageExtender added a `<style>` at the end of the `<head>` tag. Could it be that the page in question is loading CSS via JS at a later point, such that the page's CSS comes after the injected CSS?

**Comment by fphilipe** [comment]
Closing due to no response.
