### ISSUE TITLE
Possible to import libraries from external files?

### ISSUE THREAD

**Issue by weavermedia** [fphilipe/PageExtender.app#15]
I'd like to replace the audio players on a site with modern versions. Is it possible to import external files/libraries such as Plyr or WaveSurfer?

I got it working by including the Plyr source at the bottom of my site script but it would be much cleaner to import the source from an external local file.

**Comment by fphilipe** [comment]
Unfortunately, it is not possible to include additional files from the injected JS. This is due to sandboxing on macOS.

You'll have to include the script directly in the JS file that is being injected on the desired page.
