### ISSUE TITLE
Apple Silicon support?

### ISSUE THREAD

**Issue by NickChristensen** [fphilipe/PageExtender.app#17]
Hey there, do you have any plans to publish an ARM-compatible build?

**Comment by fphilipe** [comment]
Hey @NickChristensen, I've just pushed a new build ([v1.2.1-5](https://github.com/fphilipe/PageExtender.app/releases/tag/v1.2.1-5)) to the App Store and submitted it for review. All it took was to rebuild the app with the latest Xcode.

Thanks for reporting!
