### ISSUE TITLE
iOS support?

### ISSUE THREAD

**Issue by gingerbeardman** [fphilipe/PageExtender.app#20]
Now that iOS 15 can have Safari extensions I'm wondering if it would be possible to have PageExtender there?

I guess the first problem to solve would be where the user files are stored and read from?

**Comment by fphilipe** [comment]
I don't have plans (nor capacity) to look into iOS. Sorry 😊

**Comment by gingerbeardman** [comment]
No worries!

For anybody else looking I have found an alternative.

https://andadinosaur.com/launch-makeover
