### ISSUE TITLE
Javascript files are not loaded.

### ISSUE THREAD

**Issue by mikaelj** [fphilipe/PageExtender.app#25]
Safari 17.5, macOS 14.5, MacBook Pro M1.

Downloaded and built, sign to run locally.  Set both CSS and JS folders to ~/Documents/website-mods which contains default.js:

    (function() {
        console.log("default.js");
    })();

By modifying "script.js" in the app I added console.log() that shows messages are sent back to the Javascript, but in the (I guess) host part of the extension, the files aren't loaded since the arrays js and css when unpacking "message" in the onload handler. So I don't see any "Injecting" messages.

Any idea what could be wrong or where I should start looking? Thanks!

**Comment by fphilipe** [comment]
Hey @mikaelj, sorry to hear that it's not working.

Does the App Store version work? I cannot provide any further support, unfortunately.

**Comment by mikaelj** [comment]
It does! Wanted to check first if the source-built version worked (so I can improve on it) before buying, but since the store version works, I'm fine for now. Thanks! :)

**Comment by gingerbeardman** [comment]
Perhaps related #4
