### ISSUE TITLE
Sometimes stops working

### ISSUE THREAD

**Issue by gingerbeardman** [fphilipe/PageExtender.app#4]
I'm not sure how or why but after a while PageExtender stops injecting.

If I check the web inspector log, there are no messages from it.

If I restart Safari it will work again.

**Comment by fphilipe** [comment]
What do you see in Console.app when filtering for `PageExtender`?

Keep an eye out for this line:

```
Message received: 'load'
```

This line is being emitted by the following method

https://github.com/fphilipe/PageExtender.app/blob/b7588851511815f0792a01e8b72c9a796c1bc1ab/Source/Extension/SafariExtensionHandler.swift#L11-L12

which is invoked by the `script.js` on line 1:

https://github.com/fphilipe/PageExtender.app/blob/b7588851511815f0792a01e8b72c9a796c1bc1ab/Source/Extension/script.js#L1

If this is not there, that would mean that Safari is not injecting the script for some reason.

I've personally never noticed this happening.

**Comment by gingerbeardman** [comment]
I'll check next time.

So far this has happened to me twice.

**Comment by gingerbeardman** [comment]
OK, it happened again.

Nothing showing in Console.app

I do have a large (100+) number of tabs open but I can't see why that would matter?

**Comment by fphilipe** [comment]
100+ tabs, you crazy? 😂 

Joking aside, I would guess that it is a Safari bug. Not sure what can be done to be honest.

Maybe these question help in narrowing it down:

- Does that happen to any other of your plugins?
- When it stops working, does it work again on new tabs or when reloading the page?

**Comment by gingerbeardman** [comment]
You're probably correct it's a Safari bug. I'll report it as such.

I'll check other plugins, I have not noticed other things not working.

Only a restart gets it working, new tabs or reloading had no effect. Toggling extension on/off in settings also has no effect.

ps: clearing my tab backlog right now 😅

**Comment by gingerbeardman** [comment]
Another data point, sometimes I am unable to go to https://web.archive.org/web/20120201045206/http://www.example.com

And a Safari restart fixes that. Maybe related?

**Comment by gingerbeardman** [comment]
I decided to keep Console.app open until I caught the extension stop working.

```
error	00:13:02.605364 +0100	appleeventsd	<rdar://problem/11489077> A sandboxed application with pid 36623, '"PageExtender (Safari)"', checked in with appleeventsd, but its code signature could not be read and validated by appleeventsd, and so it cannot receive AppleEvents targeted by name, bundle id, or signature. Install the application in /Applications/ or some other world readable location to resolve this issue. Error=ERROR: #100013  { "NSDescription"="SecCodeCopySigningInformation() returned 100013, -." }
default	00:13:02.645998 +0100	PageExtender Extension	Message received: 'load'
error	00:13:02.646928 +0100	PageExtender Extension	Couldn't read values in CFPrefsPlistSource<0x6000027e12d0> (Domain: Q3Z639YB49.group.com.philipefatio.pageextender, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
default	00:13:02.821210 +0100	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier com.philipefatio.pageextender, type: 0: 0x7f8cf4724bd0 at /var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/AppTranslocation/2C64E0F7-6354-4159-AA55-C4C6A2BA9B7B/d/PageExtender.app
error	00:13:02.869061 +0100	tccd	Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for ACC:{ID: com.philipefatio.pageextender.extension, PID[36623], auid: 501, euid: 501, binary path: '/private/var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/AppTranslocation/2C64E0F7-6354-4159-AA55-C4C6A2BA9B7B/d/PageExtender.app/Contents/PlugIns/PageExtender Extension.appex/Contents/MacOS/PageExtender Extension'}, REQ:{ID: com.apple.appleeventsd, PID[60], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}
```

Hmm. Could this be due to me using my own compiled version?

**Comment by gingerbeardman** [comment]
I have not had this happen in the last 2 weeks

- reduced my tab count 😝
- switched to MAS release of PageExtender

👍

**Comment by fphilipe** [comment]
> switched to MAS release of PageExtender

Thanks, appreciate the support! 🍻😃

**Comment by gingerbeardman** [comment]
I had this again at ~40 tabs. I've reported it to Apple just in case it's their problem. 

Nothing jumped out in Console log.

**Comment by gingerbeardman** [comment]
> Another data point, sometimes I am unable to go to https://web.archive.org/web/20120201045206/http://www.example.com
> 
> And a Safari restart fixes that. Maybe related?

The solution to this one was to delete website data for the affected domain from Safari preferences. When Safari holds too much local data for a site (I use archive _a lot_) it gets confused and can't load pages from the domain.

**Comment by fphilipe** [comment]
Sorry to hear that you're having problems with the extension. Thanks for digging into this and reporting it to Apple.

Hopefully they fix this. I've personally yet to encounter this problem.

**Comment by gingerbeardman** [comment]
No worries. 

I'm interested if there's any better debugging I can do when it happens?

**Comment by gingerbeardman** [comment]
Console output 

https://gist.github.com/gingerbeardman/d053eb75460d362177d8a0007b7d90d7

**Comment by gingerbeardman** [comment]
It seems to be about the 50-60 tab mark that this stops working (still not sure if it's Safari stopping it or not)

**Comment by gingerbeardman** [comment]
This is interesting, I recently had to reset my .css and .js directories even though the app showed they were set and I had a green light that the extension was enabled.

Here's a log that shows the broken state (not sure how it happened), I reset the folders part way through, then you can see lots of successful load messages. 
https://gist.github.com/gingerbeardman/579f92d6315c7ac58c834dff7f37920a

Odd!

**Comment by gingerbeardman** [comment]
A workaround for this issue has been found:

https://github.com/yimingliu/reverse-image-search-safari/issues/13

Nutshell: if your extension has a toolbar button, even if it is useless and does nothing, Safari won't cut it off in certain circumstances.

**Comment by sn0wyfall** [comment]
@gingerbeardman Does this still happen to you? As far as I know, PageExtender doesn't have a toolbar button, right?

**Comment by gingerbeardman** [comment]
@sn0wyfall no, I've not noticed it happening  in recent memory. Perhaps Safari/WebKit fixed the problem?

And no, PageExtender never implemented the toolbar button workaround.

**Comment by sn0wyfall** [comment]
Nice, thanks! I'll try it out then.
