### ISSUE TITLE
PageExtender doesn't read symlinks (and I prefer if it would)

### ISSUE THREAD

**Issue by tkafka** [fphilipe/PageExtender.app#5]
Hello, I am using PageExtender to check the developer version of css file on a production website. The best way for me to do this is by creating a symlink (`ln -s`) into PageExtender folder (so that I could combine multiple css files from various repositories there).

I discovered that PageExtender ignores symlinked files - if I put a symlink into PE folder, nothing happens, when I replace it with a real file with a same content, I can see the css on a production website.

Could you please add support for symlinks? Thanks for consideration!

**Comment by fphilipe** [comment]
Hey @tkafka, I hear you! Unfortunately symbolic links that point outside of the folders that you select in PageExtender.app will not work due to the way the macOS sandbox behaves.

I'm sorry I can't give you better news.

**Comment by tkafka** [comment]
@fphilipe Thank you Philipe, this actually helped as I could find a workaround:

1. Select a folder where a real file (target of a link) is located
2. Select back the original folder with symlinks

After this macOS remembered that PageExtender has permission to the folder with a real file, and it started to work :).

**Comment by tkafka** [comment]
Maybe if I added PageExtender manually into System Prefences > Security & Privacy > Full Disk Access, it would be able to access anything and there could be a note about this at a config screen?

**Comment by fphilipe** [comment]
Great to hear that you found a solution 😊 

I'm not sure if Full Disk Access will make it work. Maybe you could try and report back? Thanks!

**Comment by tkafka** [comment]
@fphilipe Just an update to previous solution, it didn't actually work - either after a restart of Mac or of PageExtender the system took away the access to the symlinked folder. I'll see about the Full Disk access.

**Comment by tkafka** [comment]
@fphilipe ... and, Full Disk Access doesn't help. So I just made a quick oneliner script that will copy the userstyle to a common userstyle folder after editing.

**Comment by fphilipe** [comment]
Thanks for trying and sorry about the situation. Sandboxing has its pros and cons I guess 😝
